export default [
  {"description":"Electricity bills",      "amount":"150.55","type":"outflow-money","frequency":"recurrent","date":"2020-01-10"},
  {"description":"Watter bills",                  "amount":"75.55", "type":"outflow-money","frequency":"recurrent","date":"2020-01-15"},
  {"description": "Phone bills",             "amount":"99.99", "type":"outflow-money","frequency":"recurrent","date":"2020-01-23"},
  {"description":"Health insurance plan",        "amount":"300.00","type":"outflow-money","frequency":"recurrent","date":"2020-01-23"},
  {"description":"Month shopping",        "amount":"625.78","type":"outflow-money","frequency":"recurrent","date":"2020-01-23"},
  {"description":"Snacks",                "amount":"45.70", "type":"outflow-money","frequency":"eventually",  "date":"2020-01-23"},
  {"description":"Shirts",                 "amount":"95.70", "type":"outflow-money","frequency":"eventually",  "date":"2020-01-23"},
  {"description":"Electricity bills",      "amount":"125.55","type":"outflow-money","frequency":"recurrent","date":"2020-02-10"},
  {"description":"Watter bills",                  "amount":"90.15", "type":"outflow-money","frequency":"recurrent","date":"2020-02-15"},
  {"description":"Phone bills",              "amount":"99.99", "type":"outflow-money","frequency":"recurrent","date":"2020-02-23"},
  {"description":"Health insurance plan",        "amount":"300.00","type":"outflow-money","frequency":"recurrent","date":"2020-02-23"},
  {"description":"Month shopping",        "amount":"540.00","type":"outflow-money","frequency":"recurrent","date":"2020-02-25"},
  {"description":"Installments of cellphone 1/5","amount":"150.99","type":"outflow-money","frequency":"eventually",  "date":"2020-02-26"},
  {"description":"Cinema",                "amount":"45.00", "type":"outflow-money","frequency":"eventually",  "date":"2020-02-23"},
  {"description":"Electricity bills",      "amount":"97.00", "type":"outflow-money","frequency":"recurrent","date":"2020-03-10"},
  {"description":"Watter bills",                  "amount":"100.10","type":"outflow-money","frequency":"recurrent","date":"2020-03-15"},
  {"description":"Phone bills",              "amount":"99.99", "type":"outflow-money","frequency":"recurrent","date":"2020-03-23"},
  {"description":"Health insurance plan",        "amount":"300.00","type":"outflow-money","frequency":"recurrent","date":"2020-03-23"},
  {"description":"Month shopping",        "amount":"800.50","type":"outflow-money","frequency":"recurrent","date":"2020-03-17"},
  {"description":"Installments of cellphone 2/5","amount":"150.99","type":"outflow-money","frequency":"eventually",  "date":"2020-03-18"},
  {"description":"Car oil change","amount":"90.00", "type":"outflow-money","frequency":"eventually",  "date":"2020-03-23"},
  {"description":"Electricity bills",      "amount":"75.99", "type":"outflow-money","frequency":"recurrent","date":"2020-04-10"},
  {"description":"Watter bills",                  "amount":"80.33", "type":"outflow-money","frequency":"recurrent","date":"2020-04-15"},
  {"description":"Phone bills",              "amount":"99.99", "type":"outflow-money","frequency":"recurrent","date":"2020-04-23"},
  {"description":"Health insurance plan",        "amount":"300.00","type":"outflow-money","frequency":"recurrent","date":"2020-04-23"},
  {"description":"Month shopping",        "amount":"600.00","type":"outflow-money","frequency":"recurrent","date":"2020-04-25"},
  {"description":"Installments of cellphone 3/5","amount":"150.99","type":"outflow-money","frequency":"eventually",  "date":"2020-04-26"},
  {"description":"Ebook de React Js",     "amount":"85.95", "type":"outflow-money","frequency":"eventually",  "date":"2020-04-13"},
  {"description":"Electricity bills",      "amount":"125.55","type":"outflow-money","frequency":"recurrent","date":"2020-05-10"},
  {"description":"Watter bills",                  "amount":"90.15", "type":"outflow-money","frequency":"recurrent","date":"2020-05-15"},
  {"description":"Phone bills",              "amount":"99.99", "type":"outflow-money","frequency":"recurrent","date":"2020-05-23"},
  {"description":"Health insurance plan",        "amount":"300.00","type":"outflow-money","frequency":"recurrent","date":"2020-05-23"},
  {"description":"Month shopping",        "amount":"540.00","type":"outflow-money","frequency":"recurrent","date":"2020-05-25"},
  {"description":"Installments of cellphone 4/5","amount":"150.99","type":"outflow-money","frequency":"eventually",  "date":"2020-05-26"},
  {"description":"Shirts Iron Man",        "amount":"150.00","type":"outflow-money","frequency":"eventually",  "date":"2020-01-23"},
  {"description":"Electricity bills",      "amount":"200.00","type":"outflow-money","frequency":"recurrent","date":"2020-06-10"},
  {"description":"Watter bills",                  "amount":"150.00","type":"outflow-money","frequency":"recurrent","date":"2020-06-15"},
  {"description":"Phone bills",              "amount":"99.99", "type":"outflow-money","frequency":"recurrent","date":"2020-06-23"},
  {"description":"Health insurance plan",        "amount":"300.00","type":"outflow-money","frequency":"recurrent","date":"2020-06-23"},
  {"description":"Month shopping",        "amount":"559.15","type":"outflow-money","frequency":"recurrent","date":"2020-06-25"},
  {"description":"Installments of cellphone 5/5","amount":"150.99","type":"outflow-money","frequency":"eventually",  "date":"2020-06-26"},
  {"description":"Perfume",               "amount":"250.00","type":"outflow-money","frequency":"eventually",  "date":"2020-06-21"},
  {"description":"Electricity bills",      "amount":"250.00","type":"outflow-money","frequency":"recurrent","date":"2020-07-10"},
  {"description":"Watter bills",                  "amount":"90.00", "type":"outflow-money","frequency":"recurrent","date":"2020-07-15"},
  {"description":"Phone bills",              "amount":"99.99", "type":"outflow-money","frequency":"recurrent","date":"2020-07-23"},
  {"description":"Health insurance plan",        "amount":"300.00","type":"outflow-money","frequency":"recurrent","date":"2020-07-23"},
  {"description":"Month shopping",        "amount":"700.00","type":"outflow-money","frequency":"recurrent","date":"2020-07-25"},
  {"description":"Coffee machine",             "amount":"250.00","type":"outflow-money","frequency":"eventually",  "date":"2020-07-26"},
  {"description":"Pizza",                 "amount":"60.00", "type":"outflow-money","frequency":"eventually",  "date":"2020-07-19"}
]
